server:
  port: 9000
spring:
  datasource:
    username: czn_wxykt
    password: WeiXin*1300/1040
    url: jdbc:sqlserver://106.14.68.153:1983;DatabaseName=czn_alykt
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.df.xdkconsume.mapper