server:
  port: 9000
spring:
  datasource:
    username: mch_cyy
    password: Cinzn_Ykt*2018/1001
    url: jdbc:sqlserver://220.166.57.83:10433;DatabaseName=czn_yunykt
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mvc:
    view:
      prefix: 
      suffix: .html
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.df.xdkconsume.mapper

#威富通支付参数
pay-config: 
   appid: wxdc3c975af0311aef
   mch_id: 403520120170
   key: a351ddc5b84043f1382f33b381ed83a8