server:
  port: 9000
spring:
  datasource:
    username: czn_wxykt
    password: WeiXin*1300/1040
    url: jdbc:sqlserver://121.46.26.158:1980;DatabaseName=czn_xycykt
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mvc:
    view:
      prefix: 
      suffix: .html
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.df.xdkconsume.mapper

#威富通支付参数
pay-config: 
   appid: 121564
   mch_id: 7551000001
   key: 9d101c97133837e13dde2d32a5054abb